const dates = [
    { dKey: "00", dValue: "dd" },
    { dKey: "01", dValue: "01" },
    { dKey: "02", dValue: "02" },
    { dKey: "03", dValue: "03" },
    { dKey: "04", dValue: "04" },
    { dKey: "05", dValue: "05" },
    { dKey: "06", dValue: "06" },
    { dKey: "07", dValue: "07" },
    { dKey: "08", dValue: "08" },
    { dKey: "09", dValue: "09" },
    { dKey: "10", dValue: "10" },
    { dKey: "11", dValue: "11" },
    { dKey: "12", dValue: "12" },
    { dKey: "13", dValue: "13" },
    { dKey: "14", dValue: "14" },
    { dKey: "15", dValue: "15" },
    { dKey: "16", dValue: "16" },
    { dKey: "17", dValue: "17" },
    { dKey: "18", dValue: "18" },
    { dKey: "19", dValue: "19" },
    { dKey: "20", dValue: "20" },
    { dKey: "21", dValue: "21" },
    { dKey: "22", dValue: "22" },
    { dKey: "23", dValue: "23" },
    { dKey: "24", dValue: "24" },
    { dKey: "25", dValue: "25" },
    { dKey: "26", dValue: "26" },
    { dKey: "27", dValue: "27" },
    { dKey: "28", dValue: "28" },
    { dKey: "29", dValue: "29" },
    { dKey: "30", dValue: "30" },
    { dKey: "31", dValue: "31" }
]

const months = [
    { mKey: "0", mValue: "mm" },
    { mKey: "01", mValue: "January" },
    { mKey: "02", mValue: "February" },
    { mKey: "03", mValue: "March" },
    { mKey: "04", mValue: "April" },
    { mKey: "05", mValue: "May" },
    { mKey: "06", mValue: "June" },
    { mKey: "07", mValue: "July" },
    { mKey: "08", mValue: "August" },
    { mKey: "09", mValue: "September" },
    { mKey: "10", mValue: "October" },
    { mKey: "11", mValue: "November" },
    { mKey: "12", mValue: "December" }
]
module.exports  = { dates, months }