export const languages = [

    { languageKey: "0", language: "Please choose" },
    { languageKey: "1", language: "Albanian" },
    { languageKey: "2", language: "Bengali" },
    { languageKey: "3", language: "Buddhist" },
    { languageKey: "4", language: "BSL - British sign language" },
    { languageKey: "5", language: "Chinese" },
    { languageKey: "6", language: "Czechoslovakian" },
    { languageKey: "7", language: "English" },
    { languageKey: "8", language: "Farsi" },
    { languageKey: "9", language: "French" },
    { languageKey: "10", language: "German" },
    { languageKey: "11", language: "Greek" },
    { languageKey: "12", language: "Gujarati" },
    { languageKey: "13", language: "Halari" },
    { languageKey: "14", language: "Hindi" },
    { languageKey: "15", language: "Israeli (Hebrew)" },
    { languageKey: "16", language: "Italian" },
    { languageKey: "17", language: "Kosovan" },
    { languageKey: "18", language: "Lingala" },
    { languageKey: "19", language: "Luganda" },
    { languageKey: "20", language: "Macedonian" },
    { languageKey: "21", language: "Other" },
    { languageKey: "22", language: "Portuguese" },
    { languageKey: "23", language: "Punjabi" },
    { languageKey: "24", language: "Romanian" },
    { languageKey: "25", language: "Russian" },
    { languageKey: "26", language: "Slovakian" },
    { languageKey: "27", language: "Somali" },
    { languageKey: "28", language: "Sorani - Kurdish Sorani" },
    { languageKey: "29", language: "Spanish" },
    { languageKey: "30", language: "Swahili" },
    { languageKey: "31", language: "Tamil" },
    { languageKey: "32", language: "Turkish" },
    { languageKey: "33", language: "Ugandan" },
    { languageKey: "34", language: "Urdu" },
    { languageKey: "35", language: "Yugoslavian" },
    { languageKey: "36", language: "Zulu" }
];